name: Publicar Pacote Node.js

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@adonitech-solutions'
      - name: Update version in package.json
        run: |
          # Extract version from the GitHub release tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          # Update package.json with the release version
          npm version $VERSION --no-git-tag-version
      - name: Commit and push updated package files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git commit --allow-empty -m "chore: update version to ${VERSION} [skip ci]"
          git push origin HEAD:main
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}